version: "2.29.0"

services:
  ddangkong-api-dev:
    platform: linux/arm64/v8
    build:
      context: ../
      dockerfile: Dockerfile
      args:
        - SPRINT_PROFILE=dev
    ports:
      - "8080:8080"
